server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_2b28b39f45f4
    token: ae86
    app-id: wxb0cd4b5794a305af
    app-secret: e48e167619c552f8b1d94b785d6bed0b
    template_id: 6-AT74rNA_P9suOwv10aQvYxOTfE1K8K0h7CbWpdWx4

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 2021000148653884
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCTAb2oBE/w1NA8+EkeuJ2PuYOMw92E0+sqTEBuza5nXPZFEhidrJ/IJUCpowhNiEy/RbFv9h7G/CVUAmU/gbLg8Lhctw/14r/hvz39rB/XqBjthNZ9aJ2+euUIjFprpmrXxek/pBIA+43Z3jTQEzZw5WgOhlo12/xVVZ7wAvF4DDgPkaOuZTtMW8J/CTVo+blw2eEI0lV5tNg3zixmpiml6Ebb3y0KBOCtdWpzlrgINWr79v0DeHniLeoADe25qq/9Nd08tcq26+OjObYHJaxrUKEuVW317morwPV0d73C1px1pOLzjEAqmw2mRhnEIrIrjZgipDS/VHbihZc8nopNAgMBAAECggEBAJJtA3ndgbrCXwC71ikxfk9wWyXU2kq5wt2Iwg0b9gGiyPIXiklTbnuvD29oopaHktpaEtkQb6uH7650DGFrUL9ZRmmjNdSXHMVA9gA8eCMYnmvHCtYzZBwc0RDorA/Z3UY7LY9kX0J3Td2axUQUPv/IoRMGo8hN7FMbS4qJg/crvbgYkoTXuigQ1+Tkg/bduz3D6CDYpVMbX9ThcSHZBMguG5CPXcl9VUaaj/6aI3l7LFcJzCcJLGfKFECmt60cZvOU5ZTTmGOQ6X7UWscjI6409+yaNJFP0IWROV/g8iNri5WIYTUVGeJx9k1S2iMLqBA2+tzeFCIjuZFnjxcV10ECgYEA4YrMFKIBzys4P5LNsa0d/7e8tWfn/PeHpHzrrJUCQTwFwok/PnTD/lgLDTNpwwi6QGXowEBnm+rQYqeDxLdIw7WxK0R0XNnJOWCdw3QyLwA0zPjfKGnMXo21ueRNrRE1eXlUKNxZHWif1JAvTQzk5ADDZrgcxrbwxdU2A349WvkCgYEAptvnFDcuTZiS4TOC8Nx04fgtlEWfkPlUlnwoAdtnmQCnkyztAenhDPx24UQOvHbi20PnTlXxkPrQhTGj/LXoxh8UF1KtYXF02AT7/cK7umc5Q75MC9JwhN7cz9Z+n+WV0JItzCXvrc6SEFvB26ZlCJfNAy4Vkki0pu/85eyOyvUCgYEAwgroCdhYNiS4//kNfw+x/4/Uiz4aGUndKWdQW+rXRcieLABoqRNMjEazO2hAVcvscfs7hCvk9//NyRLWCyilMbvf8Zmzgy7cMMEu+jm98zH6O17in6JmcfL5pjUFnyBvIVOBVKY/BU4+NGLYTzIIuyDs/DLqjwxVmd8V2WuC3gECgYAQR4AiDsgrtekOo7HwwfF9YnM/9hL9V/YSwIY+uCNBYDj5OPbequzUEYWfsL4nUQoNDnDwyZ3J4U6a0B8Jts3BFqMlK2HTEfiuYr4bIfai1xNVMqnEtYFY1U2B0ZGFFCcrtDdXpZPexzqk8e7V+UP+NKFB4CsmnIVTjDKGVDASSQKBgBLb6Xf/mm2U5sT/9abZX63WTgHyfBE7hkdq5qsfhCSC9MHW8Vb/0ygp2tArerBUpqeztvyspMC2iLxzNoQXyaOkFgCtEQO0pR69Rs47ODCVSK/aP9LmisdNv/fLGLl/F3+VleMoDi6Fxs3sjockmyfm0FSC2JTYPL/OBGcUB9Fw
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi1/JayVMsXx4OYC8udHnO7I9oHBHFGIznVjD5ws+TlH6v24XkSwNrXh0+kACWp0WF1ztExBpywBbqTauL6sgEDG0m25sk4mgmEv0mfxXPxZ2a/MJZMZsyTr5RfhKSIyxw3DAWvkgxovD7hxS6+O+yajc4w+zTcjhpHZJpJdnVOUadGmwPhH1PTO5/1VZBnCpLG44nhaLABYKkxgWqBMm9Eh1oPLdycZFbvsspxUIvbcuXTNAsGm3G7dROfv8DZlek7dl50y6+Jbejqp7nHroGXnOF1Qv/vfvvB7k5zoVqMBOFAX6ACRkg9TBmHE2ukmDa/+oObffttPBStWNoB16PwIDAQAB
  notify_url: http://dcq.natapp1.cc/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml